-- Create Enum IF NOT EXISTS
DO $$ BEGIN
    CREATE TYPE "UserStatus" AS ENUM ('AVAILABLE', 'AWAY', 'DND', 'INVISIBLE');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Add columns to User IF NOT EXISTS
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "status" "UserStatus" DEFAULT 'AVAILABLE';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "statusText" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatarPath" TEXT;
